export const CONTACTS_FETCH = 'CONTACTS_FETCH';
export const CONTACTS_ADD = 'CONTACTS_ADD';
export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

export const KWM_STATE_CHANGED = 'KWM_STATE_CHANGED';
export const KWM_CHANNEL_CHANGED = 'KWM_CHANNEL_CHANGED';

export const KWM_DO_CALL = 'KWM_DO_CALL';
export const KWM_DO_ACCEPT = 'KWM_DO_ACCEPT';
export const KWM_DO_HANGUP = 'KWM_DO_HANGUP';
export const KWM_DO_REJECT = 'KWM_DO_REJECT';
export const KWM_DO_GROUP = 'KWM_DO_GROUP';
export const KWM_DO_IGNORE = 'KWM_DO_IGNORE';

export const KWM_CALL_NEW = 'KWM_CALL_NEW';
export const KWM_CALL_DESTROY = 'KWM_CALL_DESTROY';
export const KWM_CALL_ABORT = 'KWM_CALL_ABORT';
export const KWM_CALL_INCOMING = 'KWM_CALL_INCOMING';
export const KWM_CALL_OUTGOING = 'KWM_CALL_OUTGOING';

export const KWM_STREAMS_ANNOUNCE = 'KWM_STREAMS_ANNOUNCE';
export const KWM_STREAM_RECEIVED = 'KWM_STREAM_RECEIVED';
export const KWM_CLEAR_CALLING = 'KWM_CLEAR_CALLING';

export const KWM_PC_CONNECT = 'KWM_PC_CONNECT';
export const KWM_PC_CLOSED = 'KWM_PC_CLOSED';

export const USERMEDIA_AUDIOVIDEO_STREAM = 'USERMEDIA_AUDIOVIDEO_STREAM';
export const USERMEDIA_ERROR = 'USERMEDIA_ERROR';
export const USERMEDIA_SUCCESS = 'USERMEDIA_SUCCESS';
export const USERMEDIA_SET_DEVICEIDS = 'USERMEDIA_SET_DEVICEIDS';
export const USERMEDIA_SET_PENDING = 'USERMEDIA_SET_PENDING';

export const DISPLAYMEDIA_AUDIOVIDEO_STREAM = 'DISPLAYMEDIA_AUDIOVIDEO_STREAM';
export const DISPLAYMEDIA_SET_PENDING = 'DISPLAYMEDIA_SET_PENDING';

export const RECENTS_ADD_OR_UPDATE = 'RECENT_ADD_OR_UPDATE';
export const RECENTS_REMOVE = 'RECENTS_REMOVE';
export const RECENTS_SET = 'RECENTS_SET';
export const RECENTS_CLAIM = 'RECENTS_CLAIM';
export const RECENTS_FETCH = 'RECENTS_FETCH';
export const RECENTS_ERROR = 'RECENTS_ERROR';

export const MEET_MUTE_OR_UNMUTE = 'MEET_MUTE_OR_UNMUTE';
export const MEET_SET_MODE = 'MEET_SET_MODE';
export const MEET_LOCAL_STREAM = 'MEET_LOCAL_STREAM';
export const MEET_LOCAL_STREAM_TALKING = 'MEET_LOCAL_STREAM_TALKING';
export const MEET_SET_GUEST = 'MEET_SET_GUEST';
export const MEET_SET_AUTO = 'MEET_SET_AUTO';
export const MEET_SET_COVER = 'MEET_SET_COVER';
export const MEET_STREAM_CLASSIFIED = 'MEET_STREAM_CLASSIFIED';
export const MEET_STREAM_TALKING = 'MEET_STREAM_TALKING';

export const CHATS_MESSAGES_ADD = 'CHATS_MESSAGES_ADD';
export const CHATS_MESSAGES_RECEIVED = 'CHATS_MESSAGES_RECEIVED';
export const CHATS_MESSAGES_DELIVERY_QUEUED = 'CHATS_MESSAGES_DELIVERY_QUEUED';
export const CHATS_VISIBILITY_SET = 'CHATS_VISIBILITY_SET';
