export const SERVICE_WORKER_NEW_CONTENT = 'SERVICE_WORKER_NEW_CONTENT';
export const SERVICE_WORKER_READY = 'SERVICE_WORKER_READY';
export const SERVICE_WORKER_ERROR = 'SERVICE_WORKER_ERROR';
export const SERVICE_WORKER_OFFLINE = 'SERVICE_WORKER_OFFLINE';

export const ADD_CONTACTS = 'ADD_CONTACTS';

export const KWM_STATE_CHANGED = 'KWM_STATE_CHANGED';
export const KWM_CHANNEL_CHANGED = 'KWM_CHANNEL_CHANGED';
export const KWM_CALL_NEW = 'KWM_CALL_NEW';
export const KWM_CALL_DESTROY = 'KWM_CALL_DESTROY';
export const KWM_CALL_ABORT = 'KWM_CALL_ABORT';
export const KWM_STREAM_RECEIVED = 'KWM_STREAM_RECEIVED';

export const USERMEDIA_AUDIOVIDEO_STREAM = 'USERMEDIA_AUDIOVIDEO_STREAM';
